services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
